apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.netflix.deploymentName }}
spec:
  replicas: {{ .Values.netflix.replicas }}
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: netflix
        image: "{{ .Values.netflix.image.repository }}:{{ .Values.netflix.image.tag }}"
        imagePullPolicy: "{{ .Values.netflix.image.pullPolicy }}"
        ports:
        - containerPort: 4000
