apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.netflix.serviceName }}
spec:
  type: {{ .Values.netflix.type }}
  selector:
    app: netflix
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000

